### ISSUE TITLE
Compatibility Issue with AdvancedCompany

### ISSUE THREAD

**Issue by Noranecore** [BudgetAirpods/InsanityRemastered#10] opened 2024-01-09 18:17 UTC
Some issues with the AdvancedCompany mod. Flashlights do not slow down insanity gain. Also it seems that you gain insanity a lot quicker.

**Comment by SayounaraSilence** [comment] 2024-01-09 18:18
Also I will add that AdvancedCompany has night vision gear and I think it should also slow down insanity gain if possible.

**Comment by Agitatio** [comment] 2024-01-09 18:35
> Some issues with the AdvancedCompany mod. Flashlights do not slow down insanity gain. Also it seems that you gain insanity a lot quicker.

Can't reproduce.

**Comment by Noranecore** [comment] 2024-01-09 19:26
![image](https://github.com/BudgetAirpods/InsanityRemastered/assets/19768379/19787260-abb6-4b08-ab48-05e7bd53f821)
![image](https://github.com/BudgetAirpods/InsanityRemastered/assets/19768379/653f0456-1919-4d06-838f-a1304d673026)

some info from the AC dev

**Comment by Noranecore** [comment] 2024-01-10 05:20
Flashlight sanity drain was fixed but the night vision goggles still won't decrease sanity drain
This is probably something you would have to implement

**Comment by BudgetAirpods** [comment] 2024-01-10 06:14
> Flashlight sanity drain was fixed but the night vision goggles still won't decrease sanity drain This is probably something you would have to implement

Okay. I'll work on adding that. I apologize for not replying to your report.

**Comment by BudgetAirpods** [comment] 2024-01-10 12:14
I have added this, however it is not released yet. Thank you for suggesting this,

**Comment by Noranecore** [comment] 2024-01-13 09:03
> I have added this, however it is not released yet. Thank you for suggesting this,
> 
> EDIT: This has been released now. Let me know if you encounter any issues with it.

I forgot to reply but vision enhancer works with reducing sanity drain now.
AdvancedCompany just added another item called the helmet lamp however and that does not work to reduce sanity drain, so you would have to implement that as well.

**Comment by BudgetAirpods** [comment] 2024-01-13 10:16
> > I have added this, however it is not released yet. Thank you for suggesting this,
> > EDIT: This has been released now. Let me know if you encounter any issues with it.
> 
> I forgot to reply but vision enhancer works with reducing sanity drain now. AdvancedCompany just added another item called the helmet lamp however and that does not work to reduce sanity drain, so you would have to implement that as well.

Thank you for letting me know of the new item. I will have this fixed when I release the next update.

**Comment by Noranecore** [comment] 2024-01-18 09:30
AdvancedCompany released a new equipment (again lol) called the tactical helmet that also comes with lights

**Comment by BudgetAirpods** [comment] 2024-01-18 13:43
> AdvancedCompany released a new equipment (again lol) called the tactical helmet that also comes with lights

Damn them lol. (JK) Another one to add to the list

**Comment by YuroKashine** [comment] 2024-01-19 23:03
Can i add that Advanced company has a couple items now, 
nightvision which i think he renamed to vision enhancer.
Helmet lamp and Tactical helmet. it would be nice if these could be integrated into the sanitygain thingy

**Comment by BudgetAirpods** [comment] 2024-01-19 23:05
Fully aware and already fixed. Just doing some testing to make sure everything works properly and the update will be released.

**Comment by YuroKashine** [comment] 2024-01-19 23:27
Amazing

**Comment by BudgetAirpods** [comment] 2024-01-22 00:42
This has all been fixed. I'm going to create a new category in the discussions tab where you can report compatibility issues.

**Closed** 2024-01-22 21:02 UTC
